[package]
name = "sftsrs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.13", features = ["derive"] }
safetensors = "0.4.4"
serde = "1.0.204"
serde_json = "1.0.122"

[dev-dependencies]
hf-hub = "0.3.2"
